export const SET_DICE_PLAYER = 'SET_DICE_PLAYER'
export const GET_ROUND_DATA = 'GET_ROUND_DATA'
export const SET_ROUND_AND_PLAYER = 'SET_ROUND_AND_PLAYER'
export const SET_TURN_PLAYER = 'SET_TURN_PLAYER'