export const SET_DICE_PLAYER_ASYNC = 'SET_DICE_PLAYER_ASYNC'
export const SET_DRAW_PLAYER_ASYNC = 'SET_DRAW_PLAYER_ASYNC'
export const SET_ROUND_AND_PLAYER_ASYNC = 'SET_ROUND_AND_PLAYER_ASYNC'
export const SET_TURN_PLAYER_ASYNC = 'SET_TURN_PLAYER_ASYNC'